# Generated by Django 5.0.4 on 2024-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('weight', models.FloatField()),
                ('irrigated', models.BooleanField()),
                ('crop', models.CharField(max_length=50)),
            ],
        ),
    ]
