# Generated by Django 5.0.4 on 2024-04-06 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='harvestdata',
            name='crop',
            field=models.CharField(max_length=200),
        ),
    ]
